{% set name = "meggie" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fcb593eef41a42bfdb11a67ba3409cee0c9a15ce000069517246d00e78ca31a

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - meggie = meggie.run:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mne ==1.6.1
    - numpy ==1.26.4
    - matplotlib-base ==3.8.3
    - scikit-learn
    - python-json-logger
    - pyqt
    - h5io
    - appdirs

test:
  requires:
    - python {{ python_min }}
  imports:
    - meggie

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
