{% set name = "meggie" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1acb86914c88098ede48932820933a67d43c2d4e8b6b11efea1171eef8e1bbc1

build:
  number: 6
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - meggie = meggie.run:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - mne ==1.9.0
    - numpy
    - matplotlib-base
    - pandas
    - scikit-learn
    - python-json-logger
    - pyqt
    - h5io
    - appdirs

test:
  requires:
    - python {{ python_min }}
    - pytest
  imports:
    - meggie
  commands:
    - pytest

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
