{% set name = "meggie" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7398bbf4cb20b3b7d9fe5b1d88e48dcc041acd59a9eb500b713d5a9db2229be1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne >=0.23.0
    - matplotlib-base
    - scikit-learn
    - python-json-logger
    - pyqt >=5
    - h5py

test:
  imports:
    - meggie
  commands:
    - pip check
  requires:
    - pip

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
