{% set name = "meggie" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 082b49bfa0279a0644d9fc266ed67398bda86a661e828a7a68aff996f62bdedb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne >=1.0.0
    - matplotlib-base
    - scikit-learn
    - python-json-logger
    - pyqt >=5
    - numpy ==1.21.2
    - h5io

test:
  imports:
    - meggie

app:
  entry: meggie
  summary: "User-friendly graphical user interface to do M/EEG analysis"
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "User-friendly graphical user interface to do M/EEG analysis"

extra:
  recipe-maintainers:
    - Teekuningas
