{% set name = "meggie" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22765ae6764b10182ebd342766bb9cb857301a8ee328edd0e8c65b219329cff9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - meggie = meggie.run:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - mne ==1.9.0
    - numpy
    - matplotlib-base
    - pandas
    - scikit-learn
    - python-json-logger
    - pyqt
    - h5io
    - appdirs

test:
  source_files:
    - meggie
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-qt
  commands:
    - pytest -s meggie/actions  # run most tests

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
