{% set name = "meggie" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc09efc2b834e1b8438910e44b5a202373538c2c7bf4daeba08842c058d04cf1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points: 
    - meggie = meggie.run:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne ==1.2.3
    - matplotlib-base
    - scikit-learn
    - python-json-logger
    - pyqt
    - numpy
    - h5io

test:
  imports:
    - meggie

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
