{% set name = "meggie" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fe686461f91ca76fa85e5f059a88e44f902297bcb70c365fc27742c84201000

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mne >=1.2.0
    - matplotlib-base
    - scikit-learn
    - python-json-logger
    - pyqt >=5
    - numpy
    - h5io

test:
  imports:
    - meggie

app:
  entry: meggie
  summary: User-friendly graphical user interface to do M/EEG analysis
  type: desk

about:
  home: https://github.com/cibr-jyu/meggie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: User-friendly graphical user interface to do M/EEG analysis

extra:
  recipe-maintainers:
    - Teekuningas
